language: csharp

dotnet: 3.1.301
mono: none
sudo: false

git:
   depth: false
  
addons:
  sonarcloud:
    organization: "ita-social-projects"
    
script:
    - dotnet build src/BookCrossingBackEnd.sln -c Release 
    - dotnet test src/ApplicationTest/ApplicationTest.csproj --no-build -c Release 
    - sonar-scanner
    
deploy:
    provider: azure_web_apps
    verbose: true
    on:
        develop
