language: csharp

dotnet: 3.1.301
mono: none
sudo: false

git:
   depth: false

#env:
#    global:
#        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
#        - CODECOV_TOKEN="030b932b-3989-4b6f-91ce-b70a152bb005"

addons:
  sonarcloud:
    organization: "irynazavushchak"
    
before_script:
    - ./tools/travis-ci-install-sonar.sh

script:
    - cd src/
    - mono ../tools/sonar/SonarScanner.MSBuild.dll begin /o:"irynazavushchak" /k:"ita-social-projects_Bookcrossing-Back-End" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${SONAR_TOKEN}
    - dotnet build -c Release
    - dotnet test -c Release ApplicationTest/ApplicationTest.csproj 
    - mono ../tools/sonar/SonarScanner.MSBuild.dll end /d:sonar.login=${SONAR_TOKEN}

deploy:
    provider: azure_web_apps
    verbose: true
    on:
        develop
