language: csharp

dotnet: 3.1.301
mono: none
sudo: false

git:
   depth: false

#env:
#    global:
#        - DOTNET_CLI_TELEMETRY_OPTOUT: 1 
#        - CODECOV_TOKEN="030b932b-3989-4b6f-91ce-b70a152bb005" 
     
addons:
  sonarcloud:
    organization: "ita-social-projects"
    token:
      secure: ${SONAR_TOKEN}
    
#before_script:
#    - ./tools/travis-ci-install-sonar.sh

script:
#    - dotnet ../tools/sonar/SonarScanner.MSBuild.dll begin /o:"irynazavushchak" /k:"ita-social-projects_Bookcrossing-Back-End" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=${SONAR_TOKEN}
    - dotnet build src/BookCrossingBackEnd.sln -c Release 
    - dotnet test src/ApplicationTest/ApplicationTest.csproj --no-build -c Release 
    - sonar-scanner
#    - dotnet ../tools/sonar/SonarScanner.MSBuild.dll end /d:sonar.login=${SONAR_TOKEN}

deploy:
    provider: azure_web_apps
    verbose: true
    on:
        develop
